# Application name
spring.application.name=CONFIG-SERVER

# Port for Config Server
server.port=8888

# ==================== GITHUB CONFIGURATION ====================
# This is where Config Server reads all service config files from
# You must create a GitHub repo and put service yml files there
# Replace this URL with your own GitHub repo URL
spring.cloud.config.server.git.uri=https://github.com/yellendhar08/educommerce-config

# The branch to read config from (main or master)
spring.cloud.config.server.git.default-label=main

# Search path inside the repo (optional - if config files are inside a folder)
# spring.cloud.config.server.git.search-paths=config

# Clone on start - downloads config from GitHub when server starts
spring.cloud.config.server.git.clone-on-start=true

# ==================== EUREKA CLIENT ====================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true
